### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lobosan** [PhilippSpo/useraccounts-materialize-flow#2]
After updating the project to the latest version of meteor and after updating the plugins, isn't possible to test it out. The error I get is:

```
Error: Match error: Unknown key in field defaultLayoutRegions
```

**Comment by PhilippSpo** [comment]
Are you using the `flow-router-integration` branch of the useraccounts package?

**Comment by lobosan** [comment]
I cloned this repository https://github.com/PhilippSpo/useraccounts-materialize-flow.git

**Comment by PhilippSpo** [comment]
ok i'll quickly have a look

**Comment by PhilippSpo** [comment]
they were some issues. I updated the demo and it should work now again. Just pull and make sure you also clone the submodule in the `packages/meteor-useraccounts-core/` folder.

**Comment by lobosan** [comment]
Yes it works now
